# Generated by Django 3.2.9 on 2021-11-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_qhoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qhoice',
            new_name='Choice',
        ),
    ]
