# Generated by Django 3.2.9 on 2021-11-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelstudy', '0002_alter_person_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
