# Generated by Django 3.2.9 on 2021-11-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelstudy', '0009_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='p1', max_length=30),
            preserve_default=False,
        ),
    ]
